# Generated by Django 4.2.4 on 2023-08-11 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_challenge_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='challenge_created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 8, 3, 40, 867674, tzinfo=datetime.timezone.utc)),
        ),
    ]
