# Generated by Django 4.2.4 on 2023-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='challenge_created_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='challenge_expiration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
