# Generated by Django 4.2.4 on 2023-08-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
    ]
